import { Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto_Condensed({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={roboto.className}>
      <Toaster/>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
